services:
  monolog.logger:
    class: Monolog\Logger
    arguments: ['%app.name%']
  app.logger:
    class: Vain\Logger\Monolog\MonologAdapter
    arguments: ['@monolog.logger']
  logger.handler.abstract:
    abstract: true
    calls:
      - [setMailer, ['@monolog.formatter']]
  logger: '@app.logger'
  monolog.formatter:
    class: Vain\Logger\Formatter\MonologLineFormatter