imports:
  - { resource: 'vendor/vain/http/config/di.yml' }

services:
  monolog.logger:
    class: Monolog\Logger
  app.logger:
    class: Vain\Logger\Monolog\Handler\Dynamic\MonologCompositeHandler
    arguments: ['@monolog.logger']