parameters:
  monolog.logger.main: 'app'

services:
  monolog.logger.main:
    class: Monolog\Logger
    arguments: ['%monolog.logger.main%']
  logger.main:
    class: Vain\Logger\Monolog\MonologAdapter
    arguments: ['@monolog.logger.main']
    tags:
      - {name: logger}
  logger.handler.abstract:
    abstract: true
    calls:
      - [setFormatter, ['@monolog.formatter']]
  logger: '@logger.main'
  monolog.formatter:
    class: Vain\Logger\Monolog\MonologLineFormatter